### ISSUE TITLE
Allowing flexible number of (background) resource spectra

### ISSUE THREAD

**Issue by astaaudzi** [sizespectrum/mizer#85] opened 2019-09-09 12:15 UTC
It would be good to have a flexible way to setup multiple resource spectra and availability of these spectra to size structured groups in the model. The numbers in the spectra could be added to the numbers in the simulated size structured groups, turning the number-at-size arrays (@n or @n_pp) into a list. Each resource spectrum can have its own parameters of kappa, lambda and regeneration rate (r_pp in case of current setup). The availability of these spectra to size structured groups could be set in a separate dataframe, in a similar way as the current interaction matrix

**Comment by gustavdelius** [comment] 2019-09-09 12:32
Thanks Asta. This is a duplicate of #49 . Let's continue the discussion there.

**Closed by gustavdelius** 2019-09-09 12:32 UTC
Labels: enhancement
